services:
  myowntvapp:
    build: .
    container_name: myowntvapp
    ports:
      - "1919:1919"
    volumes:
      - ./data:/app/data
    environment:
      - PUBLIC_HOST=https://example.com
    restart: unless-stopped
